version: "3.7"
services:
  schooldb:
    image: mysql:8.0.17
    container_name: schooldb
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: '%'

  docker-school:
    #build: .
    #image: docker-school
    #container_name: docker-school
    #restart: always
    #ports:
    #  - "8080:8080"
    #networks:
    #  - school-mysql
    depends_on:
      - schooldb
    build: .
    expose:
      - "8080"
    command: "mvn clean spring-boot:run"