version: "3.7"
services:
#  schooldb:
#    image: mysql:8.0.17
#    container_name: schooldb
#    ports:
#      - "3306:3306"
#    #restart: always
#    environment:
#      MYSQL_DATABASE: school
#      MYSQL_USER: freedom
#      MYSQL_PASSWORD: 123
#      MYSQL_ROOT_PASSWORD: 123
#      MYSQL_ROOT_HOST: '%'

  docker-school:
    #depends_on:
    # - schooldb
    image: docker-school
    container_name: school
#    links:
#      - schooldb:mysql
    build: .
    ports:
      - "8080:8080"
    #restart: always