version: "3"
services:
  schooldb:
    image: mysql:8.0.17
    container_name: schooldb
    environment:
      MYSQL_DATABASE: school
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: freedom
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    networks:
      - school-network
    restart: always
  docker-school:
    build: .
    depends_on:
      - schooldb
    container_name: docker-school
    ports:
      - 8080:8080
    networks:
      - school-network
    restart: always
#    command: ["-c", "/opt/wait-for.sh schooldb:3306 && java -jar /opt/app.jar"]
#    entrypoint: ["/bin/sh"]
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://schooldb:3306/school
#      - SPRING_DATASOURCE_USERNAME=freedom
#      - SPRING_DATASOURCE_PASSWORD=ENC(j2Dr5jtMPE89o3mizMJOzA==)
networks:
  school-network: