version: "3"
services:
  schooldb2:
    image: mysql:8.0.17
    container_name: schooldb2
    environment:
      MYSQL_DATABASE: school
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: freedom
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    networks:
      - school-network
    restart: always
  docker-school:
    build: .
    depends_on:
      - schooldb2
    container_name: docker-school
    ports:
      - 8080:8080
    networks:
      - school-networky
    restart: always
networks:
  school-network: